# Generated by Django 5.1.2 on 2024-10-14 12:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auther',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
